example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml 
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import register #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import login_user #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import logout_user #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import view_wishlist_ajax
from wishlist.views import add_wishlist_ajax


app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', view_wishlist_ajax, name='wishlist_ajax'),
    path('ajax/submit/', add_wishlist_ajax, name='add_wishlist'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='/wishlist/login/')
# Create your views here.
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Jasmine Indira Wibowo',
        'last_login': request.COOKIES['last_login'],
        }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def view_wishlist_ajax(request):
    context = {
        'nama': request.user.username,
        'last_login': request.COOKIES['last_login'],
        }
    return render(request, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login/')
@csrf_exempt
def add_wishlist_ajax(req):
    if req.method == "POST":
        nama = req.POST.get("nama")
        harga = req.POST.get("harga")
        deskripsi = req.POST.get("deskripsi")
        BarangWishlist.objects.create(nama_barang=nama, harga_barang=harga, deskripsi=deskripsi)
        return HttpResponse()
    else:
        print("here")
        return redirect("wishlist:show_wishlist")
    
def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request,id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")  

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<style>
    * {
        font-family: Marker Felt;
        color: rgb(0, 0, 0);
        text-align: center;
        vertical-align: middle;
    }

    body {
        background-image: url('https://img.freepik.com/free-vector/cherry-background-desktop-wallpaper-cute-vector_53876-136873.jpg?w=2000');
    }

    td,
    input {
        text-align: left;
    }

    h1 {
        font-size: 40px;
    }

    form {
        margin: auto;
        width: 400px;
        padding: 2em;
        border: 5px solid rgb(0, 0, 0);
        border-radius: 1em;
        table-layout: fixed;
        font-size: 20px;
        background-color: rgb(255, 255, 255);
    }

    h2 {
        font-size: 15px;
    }

    a,
    a.visited {
        color: rgb(244, 24, 24);
    }
</style>

<body>
    <div class="login">

        <h1>Login 🍒</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>

                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    <td><input class="btn login_btn" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>

        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

    </div>
</body>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<style>
    * {
        font-family: Marker Felt;
        color: rgb(0, 0, 0);
        text-align: left;
        vertical-align: text-top;
    }

    body {
        background-image: url('https://img.freepik.com/free-vector/cherry-background-desktop-wallpaper-cute-vector_53876-136873.jpg?w=2000');
    }

    h1 {
        text-align: center;
        font-size: 35px;
    }

    form {
        margin: auto;
        width: 600px;
        padding: 1em;
        border: 3px solid rgb(0, 0, 0);
        border-radius: 1em;
        font-size: 15px;
        table-layout: fixed;
        background-color: rgb(255, 255, 255);
    }
</style>

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<style>
    * {
        font-family: Marker Felt;
        color: rgb(0, 0, 0);
        text-align: center;
        vertical-align: middle;
        font-size: 18px;
    }

    body {
        background-image: url('https://img.freepik.com/free-vector/cherry-background-desktop-wallpaper-cute-vector_53876-136873.jpg?w=2000');
    }

    h5 {
        font-size: 35px;
    }

    h6 {
        font-size: 15px;
    }

    p {
        font-size: 20px;
    }

    table {
        margin: auto;
        padding: 1em;
        border: 2px solid rgb(0, 0, 0);
        border-radius: 1em;
        border-collapse: collapse;
        table-layout: fixed;
        width: 80%;
        vertical-align: middle;
    }

    th {
        background-color: #ffffff;
        color: rgb(0, 0, 0);
    }

    td {
        background-color: rgb(246, 70, 70);
        color: black;
    }

    a,
    a.visited {
        color: rgb(0, 0, 0);
    }
</style>

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>

</html>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#"> {{nama}}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container-fluid">
        <button class="btn btn-light me-2" type="button" style="background-color: rgba(255, 255, 255, 0.612)"><a
                href="{% url 'wishlist:logout' %}">Logout</a></button>
    </div>
</nav>

<body>
    <br />
    <h5>🍒 Tutorial 🍒 </h5>
    <p>by {{nama}}</p>

    <table class="table table-bordered table-light" style="width:80%;">
        <thead class="table-danger">
            <tr>
                <th scope="col">Nama Barang 📦</th>
                <th scope="col">Harga Barang 💰</th>
                <th scope="col">Deskripsi 📄</th>
            </tr>
        </thead>
        <tbody>
            {% for barang in list_barang %}
            <tr>
                <th>{{barang.nama_barang}}</th>
                <th>{{barang.harga_barang}}</th>
                <th>{{barang.deskripsi}}</th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h6>Sesi terakhir login: {{ last_login }}</h6>

</body>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}

<style>
    * {
        font-family: Marker Felt;
        color: rgb(0, 0, 0);
        text-align: center;
        vertical-align: middle;
        font-size: 18px;
    }

    body {
        background-image: url('https://img.freepik.com/free-vector/cherry-background-desktop-wallpaper-cute-vector_53876-136873.jpg?w=2000');
    }

    table {
        margin: auto;
        padding: 1em;
        border: 2px solid rgb(0, 0, 0);
        border-radius: 1em;
        border-collapse: collapse;
        table-layout: fixed;
        width: 80%;
        vertical-align: middle;
        background-color: #ffffff;
    }
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    function updateTable() {
        // clear table
        var itemCount = $(".table > tbody").children().length;
        for (var i = itemCount; i >= 2; i--) {
            $(".table > tbody > tr:nth-child(" + i + ")").remove();
        }

        $.get("http://localhost:8000/wishlist/json/", function (data) {
            // fill table
            for (var i = 0; i < data.length; i++) {
                var tr = document.createElement("tr");
                var tdNama = document.createElement("td");
                tdNama.append(data[i].fields.nama_barang);
                var tdHarga = document.createElement("td");
                tdHarga.append(data[i].fields.harga_barang);
                var tdDeskripsi = document.createElement("td");
                tdDeskripsi.append(data[i].fields.deskripsi);

                tr.append(tdNama);
                tr.append(tdHarga);
                tr.append(tdDeskripsi);

                $(".table").append(tr);
            }
        });
    }

    $(document).ready(function () {
        updateTable();

        $("#add_wishlist").click(function () {
            var nama = $("#input_nama").val();
            var harga = $("#input_harga").val();
            var deskripsi = $("#input_deskripsi").val();


            $.post("http://localhost:8000/wishlist/ajax/submit/",
                {
                    nama,
                    harga,
                    deskripsi,
                },
                function (data, status) {
                    console.log("add wishlist success");
                    updateTable();
                    $("#input_nama").val("");
                    $("#input_harga").val("");
                    $("#input_deskripsi").val("");
                });
        });
    });
</script>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#"> {{nama}}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container-fluid">
        <button class="btn btn-light me-2" type="button" style="background-color: rgba(255, 255, 255, 0.612)"><a
                href="{% url 'wishlist:logout' %}">Logout</a></button>
    </div>
</nav>

<body>
    <div class="p-4">
        <br />
        <h5>🍒 Tutorial 🍒 </h5>
        <p>by {{nama}}</p>
        <table class="table table-bordered">
            <thead class="table-danger">
                <tr>
                    <th>Nama Barang 📦</th>
                    <th>Harga Barang 💰</th>
                    <th>Deskripsi 📄</th>
                </tr>
            </thead>
        </table>
        <h5>Sesi terakhir login: {{ last_login }}</h5>

        <h5 class="mt-4">Tambah Barang</h5>
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Nama Barang: </td>
                    <td><input type="text" name="nama_barang" placeholder="Nama Barang" class="form-control"
                            id="input_nama"></td>
                </tr>
                <tr>
                    <td>Harga Barang: </td>
                    <td><input type="text" name="harga_barang" placeholder="Harga Barang" class="form-control"
                            id="input_harga"></td>
                </tr>
                <tr>
                    <td>Deskripsi: </td>
                    <td><input type="text" name="deskripsi" placeholder="Deskripsi" class="form-control"
                            id="input_deskripsi"></td>
                </tr>
            </table>
        </form>
        <button id="add_wishlist" class="btn border rounded bg-info">Tambah</button>
    </div>
</body>

{% endblock content %}